use super::*;

pub(super) struct ReferenceImage {
    pub(super) name: String,
    pub(super) texture: egui::TextureHandle,
    pub(super) size: [usize; 2],
}

pub(super) struct DotStrokeApp {
    pub(super) doc: Document,
    pub(super) tool: String,
    pub(super) color: String,
    pub(super) blend: String,
    pub(super) width: i32,
    pub(super) radius: i32,
    pub(super) dither_pattern: String,
    pub(super) rounding: String,
    pub(super) pixel_preview: bool,
    pub(super) zoom: f32,
    pub(super) pan: Vec2,
    pub(super) viewport_size: Vec2,
    pub(super) last_fitted_target: Option<(i32, i32)>,
    pub(super) pending: Vec<[f32; 2]>,
    pub(super) selected: Option<(usize, usize)>,
    pub(super) selected_point: Option<usize>,
    pub(super) dragging_vector: Option<usize>,
    pub(super) current_layer: usize,
    pub(super) status: String,
    pub(super) history: History,
    pub(super) saved_document: Document,
    pub(super) close_dialog: bool,
    pub(super) allow_close: bool,
    pub(super) new_dialog: bool,
    pub(super) resolution_dialog: bool,
    pub(super) new_width: String,
    pub(super) new_height: String,
    pub(super) resolution_width: i32,
    pub(super) resolution_height: i32,
    pub(super) current_file: Option<PathBuf>,
    pub(super) native_menu: ui::NativeMenu,
    pub(super) dither_icons: HashMap<String, egui::TextureHandle>,
    pub(super) reference_window: bool,
    pub(super) reference_images: Vec<ReferenceImage>,
    pub(super) reference_selected: usize,
    pub(super) reference_zoom: f32,
    pub(super) reference_pan: Vec2,
    pub(super) reference_viewport: Vec2,
    pub(super) reference_last_size: Option<[usize; 2]>,
    pub(super) main_was_focused: bool,
}

impl Default for DotStrokeApp {
    fn default() -> Self {
        Self {
            doc: Document::default(),
            tool: "line".into(),
            color: "black".into(),
            blend: "normal".into(),
            width: 1,
            radius: 4,
            dither_pattern: "none".into(),
            rounding: "nearest".into(),
            pixel_preview: false,
            zoom: 2.0,
            pan: Vec2::ZERO,
            viewport_size: Vec2::new(800.0, 600.0),
            last_fitted_target: None,
            pending: vec![],
            selected: None,
            selected_point: None,
            dragging_vector: None,
            current_layer: 0,
            status: "Ready".into(),
            history: History::default(),
            saved_document: Document::default(),
            close_dialog: false,
            allow_close: false,
            new_dialog: false,
            resolution_dialog: false,
            new_width: DEFAULT_WIDTH.to_string(),
            new_height: DEFAULT_HEIGHT.to_string(),
            resolution_width: DEFAULT_WIDTH,
            resolution_height: DEFAULT_HEIGHT,
            current_file: None,
            native_menu: ui::NativeMenu::new(),
            dither_icons: HashMap::new(),
            reference_window: false,
            reference_images: Vec::new(),
            reference_selected: 0,
            reference_zoom: 1.0,
            reference_pan: Vec2::ZERO,
            reference_viewport: Vec2::new(640.0, 480.0),
            reference_last_size: None,
            main_was_focused: false,
        }
    }
}
